# Generated by Django 5.2 on 2025-04-29 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_alumni',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain only letters, digits, and @/./+/-/_ characters.', regex='^[\\w.@+-]+$')]),
        ),
    ]
