# Generated by Django 5.2 on 2025-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('ALL', 'All'), ('PROGRAM', 'By Program'), ('BATCH', 'By Batch')], default='ALL', max_length=10),
        ),
    ]
