# Generated by Django 5.2 on 2025-04-30 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_batch_event_program_event_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='event',
            name='program',
        ),
        migrations.RemoveField(
            model_name='event',
            name='visibility',
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event')),
            ],
        ),
    ]
