# Generated by Django 5.2 on 2025-04-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_event_batch_remove_event_program_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Updates',
        ),
    ]
