# Generated by Django 5.2 on 2025-04-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_update_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='core.event'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
