# Generated by Django 5.2 on 2025-04-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
